spring:
  application:
    name: sample-client
  profiles:
    include: common
    active: dev, eureka_dev

server:
  port: 9998
  servlet:
    context-path:

common:
  authorization:
    application:
      name: common-authorization